walkthrough update
Kuadrant/multicluster-gateway-controller pull request #194
Opened 2023-05-11 12:06 UTC by maleck13

updated ocm walkthough to take use from 1-2 clusters

2023-05-11 12:54 UTC, jasonmadigan commented
Got as far as `kubectl label managedcluster kind-mctc-control-plane ingress-cluster=true`

but then got

`kubectl label managedcluster kind-mctc-control-plane ingress-cluster=true`

2023-05-11 14:12 UTC, jasonmadigan commented
running `make local-setup OCM_SINGLE=true MCTC_WORKLOAD_CLUSTERS_COUNT=1`

at the end I get:

```
installing the hub cluster in kind-(mctc-control-plane)
./hack/local-setup.sh: line 224: clusteradm: command not found
make: *** [local-setup] Error 127
```

would've thought this would be installed via local-setup

2023-05-11 14:18 UTC, maleck13 commented
Yes it should be.  Try run 
```make clusteradm```

locally

2023-05-11 14:22 UTC, jasonmadigan commented
OK looks like expects `multicluster-gateway-controller/bin` needs to be on your `$PATH` (the makefile could be changed to make this unnecessary)

2023-05-11 15:00 UTC, jasonmadigan requested changes

2023-05-15 06:51 UTC, maleck13 commented on docs/ocm-control-plane-walkthrough.md
> +    ZONE_ROOT_DOMAIN=<replace.this>
no its actually the domain / subdomain that points to this zone

2023-05-15 08:05 UTC, maleck13 commented on docs/ocm-control-plane-walkthrough.md
> +curl -k https://sub.replace.this
you get anywhere with that ?

2023-05-15 08:58 UTC, jasonmadigan commented on docs/ocm-control-plane-walkthrough.md
> +curl -k https://sub.replace.this
No, got stuck here for some reason

2023-05-15 10:59 UTC, jasonmadigan commented on docs/ocm-control-plane-walkthrough.md
> +curl -k https://sub.replace.this
@maleck13 locally, with your setup, are you able to ping the GW IP from your host? i.e. `ping 172.32.0.1`

2023-05-15 12:10 UTC, jasonmadigan commented on docs/ocm-control-plane-walkthrough.md
> +curl -k https://sub.replace.this
Resolved- https://github.com/chipmk/docker-mac-net-connect was not started. We should probably add a note about usage of this for macOS users.

2023-05-15 13:26 UTC, maleck13 commented on docs/ocm-control-plane-walkthrough.md
> +curl -k https://sub.replace.this
added

2023-05-15 13:28 UTC, merged